# .github/workflows/lint.yml
name: golangci‑lint

on:
  push:
    branches: [master]
    paths:
      - "**/*.go"
      - .golangci.yml
      - go.mod
      - go.sum
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - "**/*.go"
      - .golangci.yml

concurrency: # kill stale lint runs on the same PR
  group: ${{ github.workflow }}‑${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # The official action handles download, cache, and annotations
      - uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5m
          only-new-issues: true
